# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================

server.port=8080

# ===============================
# CONFIGURACIÓN DE POSTGRESQL
# ===============================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

jwt.secret=MiFinanzasApiSecreta2026MiFinanzasApiSecreta2026
jwt.expiration=86400000
